# .forge-lock.hcl — DO NOT EDIT MANUALLY
# Generated by forge. Changes will be overwritten on sync.

blueprint {
  registry_url = "/Users/donaldgifford/code/forge-registry"
  name         = "bun-std"
  path         = "bun/std"
}

created_at    = "2026-07-08T03:07:10.186914Z"
last_synced   = "2026-07-08T03:07:10.186914Z"
forge_version = "0.7.0"

variables {
  bun_version                 = "1.3.14"
  git_host                    = "github.com"
  git_provider                = "github"
  license                     = "Apache-2.0"
  node_version                = "24.14.0"
  project_component_lifecycle = "production"
  project_component_owner     = "donaldgifford"
  project_component_system    = "dev-tools"
  project_component_type      = "tool"
  project_description         = "A UI for docz repos"
  project_name                = "docz-site"
  project_org                 = "donaldgifford"
  project_owner               = "donaldgifford"
  renovate_config_prefix      = "github"
}

default ".claude/settings.json" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:fc898a4fa3adc3b606f45e466e2c6ab6e7bfb0b269fdd0f63eadfc6f70974777"
}

default ".docz.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:f3fb2387d31e3b07fa2a1efdf3e974814b13113c763a7b82d7425eb2967bbcfc"
}

default ".github/CODEOWNERS" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:666453f28d6c351868d33031fd710f5ebab775b7dab797694b23eb587e161a4a"
}

default ".github/actionlint.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:8d5a2d594e5f08f6b57a814830c9511b1c3c6cb3d1341bc5295e2638f20bd884"
}

default ".github/labeler.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:d4f9c8e2a469a5b3849567391a695e80960de8962197ff8dacc57674cdc767f6"
}

default ".github/licenses-csv.tpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:181b0c267bcc0c99b7e448de827c3a9a6c65ac4e2755d2529b9985018929b2f7"
}

default ".github/workflows/changelog-regen.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:94f93e1ce75a0738ee5930433f211593d8a0b3704c7499ba2d3f1a63695f5656"
}

default ".github/workflows/changelog.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:77fc855332e849f8f08ab78aff325329f81a406a66cdddd5faac703ac7f90304"
}

default ".github/workflows/ci.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:a5188c3c1ab1ed1ad4a6f0946c77c20d6fbaa9552d33eb94d116ac8978276fa1"
}

default ".github/workflows/pr-labels.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:9d0bbe7ec5e56ac192a21ed557d5dc700375c60b555a874bc22c05eb57bd86d4"
}

default ".github/workflows/release.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:8020958cbb53657256a00111eeebc184f30c4cbf2466b90abb04464a10930729"
}

default ".github/workflows/trufflehog.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:c5b0b27a968be616c41cb318b529732ed4a9558913d490fbbfea2d11e6d71bec"
}

default ".gitignore" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:7146a544bdbfdbe6b10d072cfd53f03b415779b16e192d4173956e01c7974ddc"
}

default ".markdownlint.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:46873f7070168a2258fc63e38db76c50e0c3bfb24c122864786900ec5f91d94a"
}

default ".prettierrc.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:9f2bb9bb6b395c65c19b763d129f01b6a32ccfdea9bc46c040a9cfc683386b55"
}

default ".yamlfmt.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:5479bcd306bfb8108829c774651d94c344baec33e4592ff0472b8aa6693a8132"
}

default ".yamllint.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:58da16ddd1b296be37d3d5bf3b3eee8500c652a9ac59b18675c854a7c63b4465"
}

default "CONTRIBUTING.md.tmpl" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:8e5dcf486a7113ae77edcd28fbd399e78aed2bca7f7189f903706ac22b705b41"
}

default "README.md.tmpl" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:340752d6737c34481b8a0b9e40a8dd992c3dc303d783626a4baae526bf3b197d"
}

default "catalog-info.yaml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:f88cb17bb47e03b6e2e2084535b96d20329057c8930e6d03cc1cabb7d87fa17c"
}

default "justfile.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:9f64374ac3a22acd4d3bab51e99f1f7c2f9ab2028c3c24f1108382dc07e2b605"
}

default "mise.toml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:3b2095544ddd4350ed4c7a7812e595926c9a265e4ae9f37fc401cb8d22094e4e"
}

default "renovate.json5.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:5eaa7a79efe60aeb6f014b78512943e1f8e755068eeea0b7028871291783ffde"
}

default "scripts/labels.sh" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:37dead1ff5c5babd978afa02f4a8ac0ddd24396378b6f12cfeb808085accdcb8"
}

default ".codecov.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:61c453beec7fb0701c025e1f01b8b530aceba409777155d6497f44d48f24ee8b"
}

default ".github/dependabot.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:fab1e36ffa6b905e0c7ee83fab4435688aa3636ad7bde4dfacd7e0fe3fdf2828"
}

default ".github/workflows/codeql.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:7d7ec516e1a4f643c5c9a628131fdab368291d98d4cd22bb61b943789ddcadd2"
}

default ".github/workflows/dependabot-severity-label.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:ebc9d498c6931a6eb93bcf05915b66f29267635d5ac02514e7964d7da3885aa1"
}

default ".github/workflows/license-check.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:4671b90741cc743c3b6bc8d9b6fe132dd1ad4bb2599344c9ebcb2ae62368c106"
}

default ".github/workflows/security.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:752a8906470e7275e66dfea2985879d67f0258d29f0bd308fd73fb6899c12ded"
}

default ".gitkeep" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
}

default ".prettierignore" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:3f17529e8bdb77fbbcae0c1363a974d13279a8161b763ca4bb211ece90ad04c4"
}

default ".prettierrc.json" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:2eded62e83e4fc68d43f9968c3ec49d38043d8b218018bf728b0f57cecf1a3b0"
}

default "CHANGELOG.md" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:b64a7868c1db77e87d899af1d46c8c12d19a8c39d0b3b9a43753f75c1a0718aa"
}

default "bunfig.toml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:f012963c8aa1c8e53278e6b13fe7f65273b2d6de6284df735a39a14e704615f9"
}

default "cliff.toml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:00d074ae57f28c08709961f8dd5b01ff6c423bb29a29323a8bab2d743f74699f"
}
